import os
import json
import datetime as dt

# "id": "707219482610761849",
# "type": "Default",
# "timestamp": "2020-05-05T13:17:44.157+00:00",
# "timestampEdited": null,
# "callEndedTimestamp": null,
# "isPinned": false,
# "content": "il faut que je me pose pour lire ça avant",
# "author": {
#  "id": "389088437778644992",
#  "name": "Peaupote",
#  "discriminator": "0753",
#  "nickname": "Peaupote",
#  "color": null,
#  "isBot": false,
#  "avatarUrl": "https://cdn.discordapp.com/avatars/389088437778644992/7946585345d7ca64f7496fac82f5e178.png?size=128"
# },
# "attachments": [],
# "embeds": [],
# "reactions": [],
# "mentions": []

DEFAULT_PATH = "./discord"

def count_messages_json(counter,
                        chats,
                        sender=None,
                        attachs=True,
                        multattachs=False):
    for message in chats["messages"]:
        if "author" not in message or "name" not in message["author"] or (
                sender is not None
                and message["author"]["name"] not in sender):
            continue

        date = dt.datetime.strptime(
            message["timestamp"][:message["timestamp"].rindex('T')],
            "%Y-%m-%d").date()

        if "content" in message:
            counter[date] = counter.get(date, 0) + 1

        if not attachs:
            continue

        nbattachs = len(message["attachments"])
        if multattachs:
            counter[date] = counter.get(date, 0) + nbattachs
        else:
            counter[date] = counter.get(date, 0) + 1

def count_messages(account,
                   counter,
                   path=DEFAULT_PATH,
                   sender=None,
                   attachs=True,
                   multattachs=False):
    """Adds the number of messages for each date to the counter.

    Arguments:
    account: the name of the json file for which we want to count the messages.
    counter: the dictionary containing the number of messages for each date.
    path: the path to the directory containing the conversations. Defaults to  DEFAULT_PATH.
    sender: either a string corresponding to the name of a sender, a set of senders, or None. If None, all senders are counted.
    attachs: a boolean indicating whether attachments (files, gifs, stickers, images, videos, etc) are counted as messages. Defaults to True.
    multattachs: a boolean indicating whether multiple attachments sent at once are counted several messages.
    Default to False. Doesn't matter if `attachs` is False.
    """

    with open(f"{path}/{account}", encoding='utf8') as reader:
        chats = json.load(reader)

        if isinstance(sender, str):
            sender = {sender}

        count_messages_json(counter, chats, sender, attachs, multattachs)

def count_all_messages(counter,
                       sender=None,
                       path=DEFAULT_PATH,
                       attachs=True,
                       multattachs=False):
    for file in os.listdir(path):
        if file.endswith(".json") and os.path.isfile(f"{path}/{file}"):
            with open(f"{path}/{file}", encoding='utf8') as reader:
                chats = json.load(reader)
                count_messages_json(counter, chats, sender, attachs,
                                    multattachs)

# Initiate Discord command line parameters
def init(parser):
    group = parser.add_argument_group("discord", "Discord options")

    # Discord parameters
    group.add_argument(
        '--dcaccount',
        type=str,
        action="store",
        help=
        "the name of the chat we want to count messages from. Has to be specified to count Discord messages"
    )
    group.add_argument(
        '--dcpath',
        type=str,
        action="store",
        default=DEFAULT_PATH,
        help=
        f"the path to the json file generated by Discord. Defaults to \"{DEFAULT_PATH}\""
    )
    group.add_argument(
        '--dcsender',
        type=str,
        action='append',
        default=None,
        help=
        "the list of considered senders. If not specified, all messages are counted. Use once per sender"
    )

def parse(counter, values):
    if values["all"]:
        if values["dcsender"] is not None:
            count_all_messages(counter,
                               values["dcsender"],
                               path=values["dcpath"],
                               attachs=not values["no_attachs"],
                               multattachs=values["multi_attachs"])
    elif values["dcaccount"] is not None:
        count_messages(values["dcaccount"],
                       counter,
                       sender=values["dcsender"],
                       path=values["dcpath"],
                       attachs=not values["no_attachs"],
                       multattachs=values["multi_attachs"])
